version: 2

models:
  - name: int__ohlcv_clean
    description: "Clean, deduped BTCUSDT 1h bars"
    config:
      contract: {enforced: true}
      access: public
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 500
    columns:
      - name: timestamp
        data_type: timestamp
        tests:
          - not_null
          - unique
          - monotonic_timestamp        # custom test below
      - name: dt
        data_type: date
        tests: [not_null]
      - name: open
        data_type: float64
        tests: [not_null]
      - name: high
        data_type: float64
        tests: [not_null]
      - name: low
        data_type: float64
        tests: [not_null]
      - name: close
        data_type: float64
        tests: [not_null]
      - name: volume
        data_type: float64
        tests: [not_null]
      - name: symbol
        data_type: string
        tests: [accepted_values: {values: ["BTCUSDT"]}]
      - name: interval_
        data_type: string
        tests: [accepted_values: {values: ["1h"]}]
