version: 2

models:
  - name: dq__test_failures_daily
    description: "Daily rollup of dbt test failures by test and model."
    config:
      contract:
        enforced: true
      access: public
    columns:
      - name: as_of_date
        data_type: date
      - name: test_name
        data_type: string
      - name: model_name
        data_type: string
      - name: failed_rows
        data_type: int64

  - name: dq__freshness_history
    description: "History of source freshness runs."
    config:
      contract:
        enforced: true
      access: public
    columns:
      - name: generated_at
        data_type: datetime
      - name: source_name
        data_type: string
      - name: status
        data_type: string
      - name: max_loaded_at
        data_type: timestamp
      - name: hours_since_last_load
        data_type: float64
